version: "2"

services:

  web:
    env_file: ".env"
    environment:
      ALLOWED_HOST: "reviews.mgomez.ch"
    command: ["production"]

  haproxy:
    build:
      context: "services/haproxy"
    environment:
      CERTS: "reviews.mgomez.ch"
      EMAIL: "targen@gmail.com"
      SERVICE_80_NAME: "reviews-http"
      SERVICE_80_CHECK_TCP: "true"
      SERVICE_80_CHECK_INITIAL_STATUS: "passing"
      SERVICE_80_CHECK_INTERVAL: "30s"
      SERVICE_80_CHECK_TIMEOUT: "15s"
      SERVICE_80_TAGS: "prefixhttp-reviews.mgomez.ch/"
      SERVICE_443_NAME: "reviews-https"
      SERVICE_443_CHECK_TCP: "true"
      SERVICE_443_CHECK_INTERVAL: "30s"
      SERVICE_443_CHECK_TIMEOUT: "15s"
      SERVICE_443_TAGS: "prefixhttps-reviews.mgomez.ch/"
    links:
      - "web:www"
    restart: "always"
    volumes:
      - "./data/letsencrypt:/etc/letsencrypt"

networks:
  default:
    external:
      name: "localservices_default"
