version: "2"

services:

  web:
    env_file: ".env"
    environment:
      ALLOWED_HOST: "reviews.mgomez.ch"
    command: ["production"]

  haproxy:
    build:
      context: "services/haproxy"
    restart: "always"
    ports:
      - "80:80"
      - "443:443"
    links:
      - "web:www"
    environment:
      CERTS: "reviews.mgomez.ch"
      EMAIL: "targen@gmail.com"
    volumes:
      - "./data/letsencrypt:/etc/letsencrypt"
