version: "2"

services:

  web:
    build:
      context: "."
      dockerfile: "services/web/Dockerfile"
    restart: "always"
    labels:
      SERVICE_NAME: "reviews"
    links:
      - "postgres"
    volumes:
      - "./data/migrations:/usr/src/app/reviews/migrations"

  postgres:
    image: "postgres:9.6"
    restart: "always"
    environment:
      POSTGRES_DB: "reviews"
      POSTGRES_USER: "reviews"
      POSTGRES_PASSWORD: "reviews"
    volumes:
      - "./data/postgres/data:/var/lib/postgresql/data"
      - "./data/postgres/log:/var/log/postgresql"
